### ISSUE TITLE
when will you support npm 3.x ?

### ISSUE THREAD

**Issue by smartmouse** [danmasta/ng-resize#6]
In your dependencies, you have npm 2.x,  many of the newer node version. e.g. node 6.x comes with npm 3.x already.  Is it possible to update your engine to npm 3.x  in the package.json ?
Thanks in advance.

**Comment by danmasta** [comment]
Hi @smartmouse thanks for pointing this out! Npm engine field is now set to `npm: ">=2"` a57d10eccb718f9e5ea968f29081c12b1c42cb81
